<?php
namespace common\models\mysql;

use common\helpers\DateHelper;

class ActiveRecord extends \yii\db\ActiveRecord
{

    const STATUS_ACTIVE = 0;
    const STATUS_DELETED = 1;

    public function scenarios()
    {
        return [static::SCENARIO_DEFAULT => $this->attributes()];
    }

    public function beforeSave($insert)
    {
        if($insert == true)
            $this->setAttribute('create_time',(string)DateHelper::now());
        $this->setAttribute('update_time',(string)DateHelper::now());
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function add(array $data)
    {
        if($this->load($data,'') && $this->save()) return $this->id;
        return false;
    }
}