<?php
namespace common\models\mysql;

class MediaModel extends ActiveRecord
{
    const IS_RECOMMEND = 1;
    const NOT_RECOMMEND = 0;

    public static function tableName()
    {
        return "{{%media}}";
    }

    public function getLines()
    {
        return $this->hasMany(MediaLinesModel::className(),['source_id' => 'id'])
            ->where(['status' => MediaLinesModel::STATUS_ACTIVE])
            ->select(['source_id','lang_type','line_number','content','start_time','end_time'])
            ->orderBy(['line_number' => SORT_ASC,'lang_type' => SORT_ASC])
            ->asArray();
    }

    public function getCategory()
    {
        return $this->hasOne(MediaCategoryModel::className(), ['id' => 'cate_id'])
            ->select(['id','name','name_en']);
    }

    public function beforeSave($insert)
    {
        //更新视频音频内容
        if($this->source_type != 3 and $this->id){
            $oldLangType = $this->getOldAttribute('lang_type');
            $oldLangType = $oldLangType ? explode(',',$oldLangType) : [];
            $langType  = $this->lang_type ? explode(',', $this->lang_type) : [];
            $langType = array_unique(array_filter(array_merge($oldLangType, $langType)));
            $this->lang_type = implode(',', $langType);
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}